#!/bin/sh

# This pipeline could be separated from libsequence/analysis with ~1d work
# but givin the low probability of reuse, I won't bother.
# Steps in pipeline:

#1) Install modified libsequence
cd libsequence*
./configure
sudo make install

#2) Install MonKeyTest
cd analysis*
automake
autoconf
./configure
sudo make install

#3) Run analysis script to compute the time series of alpha values
python compute_alphas.py > alphas.tsv

#4) Run R script to plot the data!
Rscript plot_alphas.r